services:
  redis:
    image: redis:7-alpine
    container_name: cache
    ports:
      - 6379:6379

  valkey:
    image: valkey/valkey:8-alpine
    container_name: valkey-cache
    command: valkey-server --port 8080
    ports:
      - 8080:8080
    networks:
      - valkey-network

  valkey-cluster:
    image: valkey/valkey:8-alpine
    container_name: valkey-cluster
    command: >
      sh -c "
        valkey-server --port 8081 --cluster-enabled yes &
        sleep 5;
        valkey-cli -p 8081 cluster addslotsrange 0 16383;
        tail -f /dev/null
      "
    ports:
      - 8081:8081
    networks:
      - valkey-network

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamo
    ports:
      - 8000:8000

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  etcd:
    image: bitnamilegacy/etcd:3.5
    container_name: etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
    ports:
      - 2379:2379

networks:
  valkey-network:
    driver: bridge
